[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "surrealdb_embedding_model"
version = "0.1.0"
dependencies = [
    "surrealdb ==1.0.4",
    "torch",
    "pandas",
    "tqdm"
]